# Generated by Django 5.1.1 on 2024-10-05 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nameF', models.CharField(max_length=30, null=True)),
                ('ittype', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('medical', models.BooleanField()),
                ('home', models.BooleanField()),
                ('introduction', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('mainimage', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('image1', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('image2', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('image3', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('sunlight', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
                ('temprature', models.CharField(max_length=20)),
                ('amount', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('store', models.CharField(max_length=30)),
                ('suggestionplants', models.CharField(max_length=30)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
