# Generated by Django 5.1.1 on 2025-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addfield',
            name='author',
        ),
        migrations.AlterField(
            model_name='addfield',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='country',
            field=models.CharField(max_length=30, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='discount',
            field=models.IntegerField(null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='home',
            field=models.BooleanField(verbose_name='home'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='humidity',
            field=models.CharField(max_length=20, verbose_name='humidity'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='image1',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='', verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='image2',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='', verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='image3',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='', verbose_name='image3'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='introduction',
            field=models.TextField(max_length=500, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='ittype',
            field=models.CharField(max_length=30, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='mainimage',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='', verbose_name='main image'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='medical',
            field=models.BooleanField(verbose_name='medical'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='name',
            field=models.CharField(max_length=30, verbose_name='english name'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='nameF',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='store',
            field=models.CharField(max_length=30, verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='suggestionplants',
            field=models.CharField(max_length=30, verbose_name='suggestionplants'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='sunlight',
            field=models.CharField(max_length=20, verbose_name='sunlight'),
        ),
        migrations.AlterField(
            model_name='addfield',
            name='temprature',
            field=models.CharField(max_length=20, verbose_name='temprature'),
        ),
    ]
